- name: my second playbook
  hosts: ubuntu
  become: true
  tasks:

 
    - name: installing httpd package
      apt:
        name: apache2
        state: latest

    - name: start the service of apache server
      service:
        name: apache2
        state: started
